sudo: required

language: java
jdk:
 - oraclejdk8

services:
 - docker

script:
 - mvn package

after_success:
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t $DOCKER_USERNAME/springboot-users .;
    echo "Testing Docker Hub credentials...";
    docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD;
    echo "Docker Hub credentials are working";
    docker push $DOCKER_USERNAME/springboot-users;
    fi