version: '2'
services:
  mongo-db-container:
    container_name: "mongo-db-container"
    image: mongo
    volumes:
      - "./.data/mongo:/data/mongo"
    environment:
      - MONGO_INITDB_DATABASE = TP_CLOUD
    restart: always

  users-application-container:
    container_name: "users-application-container"
    depends_on:
      - mongo-db-container
    image: franckparis/springboot-users
    links:
      - mongo-db-container
    ports:
      - "80:8080"
    restart: always